@URL=  http://localhost:3000/all-my-links-api/v1/auth

### Sign Up
POST {{URL}}/signUp
Content-Type: application/json

{
    "password": "G7815GRO",
    "email": "olivergr1014@gmail.com",
    "nickName": "olivergr1014",
    "fullName": "Oliver Guerro Ruiz"
}

### Sign In
POST {{URL}}/signIn
Content-Type: application/json

{
    "nickNameOrEmail": "juan872",
    "password": "1234"
}

### Verify Email

