@URL=  http://localhost:3000/all-my-links-api/v1/links
@TOKEN = 
POST {{URL}}
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "titleLink": "minecraft",
    "link": "http://www.minecraft.com",
    "socialName": "minecraft",
    "socialIcon": "http://www.minecraft.com/favicon.ico"
}