@URL=  http://localhost:3000/all-my-links-api/v1/links

POST {{URL}}
Content-Type: application/json

{
    "titleLink": "Github",
    "link": "http://www.github.com",
    "socialName": "github",
    "socialIcon": "http://www.github.com/favicon.ico",
    "user": "62772f45804d5d68b3b82c87"
}